[project]
name = "library-manager"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "streamlit>=1.43.2",
    "matplotlib>=3.7.0",
    "seaborn>=0.13.2"
]
